aider: Added error handling for missing 'output_vectors.npy' file in Face_Editing.py.
# Aider chat conversation:

USER: From (uriginal): https://drive.google.com/uc?id=1MEGjdvVpUsu1jB4zrXZN7Y4kBBOzizDQ
From (redirected): https://drive.google.com/uc?id=1MEGjdvVpUsu1jB4zrXZN7Y4kBBOzizDQ&confirm=t&uuid=69e1b931-39f7-42eb-8bf1-18e3eeb80017
To: /Users/akurz/alexhkurz-at-git/StyleGAN-Face-Morphing/InterFaceGAN/karras2019stylegan-ffhq-1024x1024.pkl
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 325M/325M [00:26<00:00, 12.3MB/s]
mv: cannot stat '/content/InterFaceGAN/karras2019stylegan-ffhq-1024x1024.pkl': No such file or directory
'output_vectors.npy' does not exist.
Traceback (most recent call last):
  File "/Users/akurz/alexhkurz-at-git/StyleGAN-Face-Morphing/Face_Editing.py", line 94, in <module>
    print("%d latent vectors of shape %s loaded from %s!" %(final_w_vectors.shape[0], str(final_w_vectors.shape[1:]), 'output_vectors.npy'))
                                                            ^^^^^^^^^^^^^^^
NameError: name 'final_w_vectors' is not defined

ASSISTANT: The error message indicates that the script is trying to access the variable `final_w_vectors` before it is defined. This happens because the file `output_vectors.npy` does not exist in the specified location.

To fix this, we need to ensure that the file `output_vectors.npy` is in the correct directory before running the script. If the file is not in the correct directory, you should move it there. If the file does not exist, you will need to generate it using the appropriate method.

If you are sure that the file is in the correct location, we can add a check in the script to stop execution and print an error message if the file does not exist. This will make it easier to diagnose the problem if it occurs again in the future.

Here is the *SEARCH/REPLACE* block to add this check:

Face_Editing.py
```python
<<<<<<< SEARCH
import numpy as np
if os.path.exists('output_vectors.npy'):
    final_w_vectors = np.load('output_vectors.npy')
else:
    print("'output_vectors.npy' does not exist.")
=======
import numpy as np
if os.path.exists('output_vectors.npy'):
    final_w_vectors = np.load('output_vectors.npy')
else:
    print("'output_vectors.npy' does not exist.")
    sys.exit("'output_vectors.npy' does not exist.")
>>>>>>> REPLACE
```

This change will cause the script to stop execution and print an error message if `output_vectors.npy` does not exist.