aider: Changed absolute path to relative in os.chdir to fix FileNotFoundError.
# Aider chat conversation:

USER: Warning: CUDA toolkit not found. Some functionality may not be available.
Now running TensorFlow version 2.15.0 on Colab!
sh: nvcc: command not found
Cloning into 'InterFaceGAN'...
remote: Enumerating objects: 127, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 127 (delta 5), reused 4 (delta 4), pack-reused 107
Receiving objects: 100% (127/127), 2.05 MiB | 2.18 MiB/s, done.
Resolving deltas: 100% (15/15), done.
Traceback (most recent call last):
  File "/Users/akurz/alexhkurz-at-git/StyleGAN-Face-Morphing/Face_Editing_Notebook.py", line 61, in <module>
    os.chdir('/content/InterFaceGAN/')
FileNotFoundError: [Errno 2] No such file or directory: '/content/InterFaceGAN/'

ASSISTANT: The error message indicates that the script is trying to change the current working directory to '/content/InterFaceGAN/', but this directory does not exist. This is likely because the script was originally written to be run in a Google Colab environment, where the '/content/' directory is the default working directory.

To fix this, we can replace the absolute path '/content/InterFaceGAN/' with a relative path 'InterFaceGAN/'. This will make the script look for the 'InterFaceGAN/' directory in the current working directory, rather than at the root of the file system.

Here is the *SEARCH/REPLACE* block:

Face_Editing_Notebook.py
```python
<<<<<<< SEARCH
os.chdir('/content/InterFaceGAN/')
=======
os.chdir('InterFaceGAN/')
>>>>>>> REPLACE
```